### ISSUE TITLE
Missing dependency Flask-WTF

### ISSUE THREAD

**Issue by Mentorius** [pclipse/beammp-webgui#2]
Followed the readme, got error at startup:
File "D:\BeamMP\WebGUI\app.py", line 6, in <module>
    from flask_wtf import FlaskForm
ModuleNotFoundError: No module named 'flask_wtf'

Seems this dependency is missing in the readme.
pip install Flask-WTF

**Comment by pclipse** [comment]
Hello,

Thanks for bringing this to my attention, I've updated the readme.md accordingly. You just need to install the flask-wtf python dependency. You'll see I changed step 3.

I see you ran the flask-wtf install command. Did that sort the issue?

**Comment by Mentorius** [comment]
Yes, after installing flask-wtf it runs fine.

**Comment by pclipse** [comment]
Okay great! Cheers.
